[build]
  publish = "."

[[headers]]
  for = "/data/preset.json"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/assets/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
